### PR TITLE
Update JSON reporting schema

### LINKED ISSUE #100: Refactor JSON reporting schema
Refactor the JSON output of `modelscan.scan()` and the JSONReport schema to match the example below:

```
{
    "summary": {
        "total_issues_by_severity": {
            "LOW": 0,
            "MEDIUM": 0,
            "HIGH": 1,
            "CRITICAL": 1
        },
        "total_issues": 2,
        "input_path": "/tmp/test_model",
        "modelscan_version": "0.1",
        "timestamp": datetime.datetime.now(),
        "skipped": {
            "total_skipped": 0,
            "skipped_files": []
        },
        "scanned": {
            "total_scanned": 0,
            "scanned_files": []
        }
    },
    "issues": [
        {
            "description": "Use of unsafe operator 'get' from module 'requests.api'",
            "operator": "get",
            "module": "requests.api",
            "source": "/tmp/test_model/malicious6.pkl",
            "scanner": "pytorch",
            "severity": "HIGH"
        },
        {
            "description": "Use of unsafe operator 'eval' from module 'builtins'",
            "operator": "eval",
            "module": "builtins",
            "source": "/tmp/test_model/malicious1_v4.pkl",
            "scanner": "pytorch",
            "severity": "LOW"
        }
    ],
    "errors": []
}
```

### PR DESCRIPTION
**Pull request by mehrinkiani**
This PR updates JSON reporting schema as outlined in #100. The field `timestamp: datetime.datetime.now()` has isoformat, i.e. `timestamp: datetime.datetime.now().isoformat` to make it JSON serializable.

Closes #100

### CODE REVIEW

**Review by willarmiros — APPROVED** [review]
LGTM, and no problem on the ISO Format! @mehrinkiani can you possibly post a sample output with the new format (showing 1 or 2 vulns) for our reference?

**Comment by mehrinkiani** [comment]
Thank you for the review @willarmiros. Here is a JSON report generated by scanning Tensorflow safe and unsafe models from [notebooks/tensorflow_fashion_mnist.ipynb](https://github.com/protectai/modelscan/blob/main/notebooks/tensorflow_fashion_mnist.ipynb)

```
{
    "summary": {
        "total_issues_by_severity": {
            "LOW": 0,
            "MEDIUM": 0,
            "HIGH": 2,
            "CRITICAL": 0
        },
        "total_issues": 2,
        "input_path": "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels",
        "modelscan_version": "0.0.0",
        "timestamp": "2024-02-09T11:19:02.261556",
        "scanned": {
            "total_scanned": 6,
            "scanned_files": [
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/fingerprint.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/keras_metadata.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/saved_model.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/fingerprint.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/keras_metadata.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/saved_model.pb"
            ]
        }
    },
    "issues": [
        {
            "description": "Use of unsafe operator 'ReadFile' from module 'Tensorflow'",
            "operator": "ReadFile",
            "module": "Tensorflow",
            "source": "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/saved_model.pb",
            "scanner": "modelscan.scanners.SavedModelTensorflowOpScan",
            "severity": "HIGH"
        },
        {
            "description": "Use of unsafe operator 'WriteFile' from module 'Tensorflow'",
            "operator": "WriteFile",
            "module": "Tensorflow",
            "source": "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/saved_model.pb",
            "scanner": "modelscan.scanners.SavedModelTensorflowOpScan",
            "severity": "HIGH"
        }
    ],
    "errors": []
}
```

**Comment by willarmiros** [comment]
@mehrinkiani thank you for this, it will be super helpful for us! I noticed there is no `skipped` field in the summar, is that expected when no files are skipped?

**Comment by mehrinkiani** [comment]
@willarmiros thank you for the feedback. To view skipped files scan command needs a `--show-skipped` [argument](https://github.com/protectai/modelscan?tab=readme-ov-file#using-modelscan-via-cli). I generated the previous report without `--show-skipped`.  Below is the report with `--show-skipped`

```
{
    "summary": {
        "total_issues_by_severity": {
            "LOW": 0,
            "MEDIUM": 0,
            "HIGH": 2,
            "CRITICAL": 0
        },
        "total_issues": 2,
        "input_path": "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels",
        "modelscan_version": "0.0.0",
        "timestamp": "2024-02-09T11:31:10.138955",
        "skipped": {
            "total_skipped": 4,
            "skipped_files": [
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/variables/variables.data-00000-of-00001",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/variables/variables.index",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/variables/variables.data-00000-of-00001",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/variables/variables.index"
            ]
        },
        "scanned": {
            "total_scanned": 6,
            "scanned_files": [
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/fingerprint.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/keras_metadata.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/saved_model.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/fingerprint.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/keras_metadata.pb",
                "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/safe_model/saved_model.pb"
            ]
        }
    },
    "issues": [
        {
            "description": "Use of unsafe operator 'ReadFile' from module 'Tensorflow'",
            "operator": "ReadFile",
            "module": "Tensorflow",
            "source": "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/saved_model.pb",
            "scanner": "modelscan.scanners.SavedModelTensorflowOpScan",
            "severity": "HIGH"
        },
        {
            "description": "Use of unsafe operator 'WriteFile' from module 'Tensorflow'",
            "operator": "WriteFile",
            "module": "Tensorflow",
            "source": "/Users/mehrinkiani/Documents/modelscan/notebooks/TensorFlowModels/unsafe_model/saved_model.pb",
            "scanner": "modelscan.scanners.SavedModelTensorflowOpScan",
            "severity": "HIGH"
        }
    ],
    "errors": []
}
```

**Pull request merged**
